name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pull Request Branch
      uses: actions/checkout@v2

    # We also need the origin/develop branch to compare with in order to determine
    # which packages to test
    - name: Fetch Develop branch 
      run:
        git fetch --no-tags --prune --depth=1 origin +refs/heads/develop:refs/remotes/origin/develop
    - name: Install Node
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 13.x

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Test changed packages
      run: yarn test --since origin/develop
